name: Build IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer

      - name: Grant execute permission
        run: chmod +x ./build-ipa.sh

      - name: Run IPA Build Script
        run: ./build-ipa.sh

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        if: always() # Uploads even if previous step had output issues
        with:
          name: AirCard-IPA
          path: |
            **/*.ipa
            **/*.app
            build/
